server:
  port: 9000
  servlet:
    context-path: /gilderose

spring.data.elasticsearch:
  repositories.enabled: true
  cluster-nodes: localhost:9300
  cluster-name: docker-cluster

tele.item-update.cron: 0 0 1 * * *